### ISSUE TITLE
is that the best practice for docker image in unraid with uid=99 gid=100 umask=000?

### ISSUE THREAD

**Issue by VergilGao** [ich777/docker-debian-bullseye#1]
i used to build a docker image with s6-overlay, it provide a command ```s6-setuidgid``` can help me to run a program with a specific user in docker container.
when i tried to migration my services from debian to unraid, i got many permission issues.
then i found that all the files in unraid belong to the user "nobody".
i dont know how it works with smb to inmplement muti-user permission, but i think if i made all the files create by docker container belong to "nobody", and set umask=000, the  permission issues would be solved.
is that right? and is that the best practice in unraid?

**Comment by ich777** [comment]
> i dont know how it works with smb to inmplement muti-user permission, but i think if i made all the files create by docker container belong to "nobody", and set umask=000, the permission issues would be solved.
> is that right? and is that the best practice in unraid?

I think I don't quiet understand all of what you are writing but in general all user files and all files who are created by a Docker container on Unraid should be owned by UID 99 (users) and GID 100 (nobody).

The part that I don't understand is for SAMBA, do you want multiple samba users for different shares or am I wrong?


> when i tried to migration my services from debian to unraid, i got many permission issues.

How did you migrate the files and did you import all the files into my Debian-Bullseye container?


> i used to build a docker image with s6-overlay, it provide a command `s6-setuidgid` can help me to run a program with a specific user in docker container.

I basically do this all on my own in my containers because I try to use as less third party software as possible, at least for Docker.

**Comment by VergilGao** [comment]
> How did you migrate the files and did you import all the files into my Debian-Bullseye container?

i have some docker-compose files in my elder debian server to create my services,this is one of them:
```
version: "3.1"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1024
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK=002
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/downloads
    network_mode: "host"
    restart: unless-stopped
```
when i change the environment args to PUID=99 PGID=100 UMASK=002,then start this service in unraid, i found i lose my 
write permission to the downloads folder. I realized i must change the umask to 000, then i fixed it.

> I basically do this all on my own in my containers because I try to use as less third party software as possible, at least for Docker.

how to run program with 99:100? by run docker as -user 99:100 -e UID=99 -e GID=100 UMASK=000 and add following code when startup?
```
usermod -u ${UID} ${USER}
usermod -g ${GID} ${USER}
umask ${UMASK}
```
> The part that I don't understand is for SAMBA, do you want multiple samba users for different shares or am I wrong?

yes, i want multiple samba users for different folder and i used to inmplement this by setfacl in my elder server. it dosent work well and i lost my patience, so i move to unraid now.

:(
i have to sleep now, its 22:34 in my side, thanks for your information about unraid and your docker scripts. they are helpful for me.
